Add enemies and bug fix
justinro-underscore/DinoJam2023 pull request #18
Opened 2023-09-15 01:47 UTC by vchadha

bug fix for initial scene name
basic prefabs for very basic enemies

2023-09-15 04:43 UTC, justinro-underscore requested changes
Eh I'm not feelin it

2023-09-16 16:25 UTC, vchadha commented
> Eh I'm not feelin it

son of a...... 😆 

but also i didn't like this before so changed it lmao

2023-09-16 22:35 UTC, justinro-underscore requested changes

2023-09-16 22:35 UTC, justinro-underscore commented on Assets/Scripts/GameElements/EnemyMovementController.cs
> +            if (child.tag == Constants.pathTag)
This is minor, but I think in Unity usually when comparing tags you want to use the `child.CompareTag(Constants.pathTag)` function

2023-09-16 22:35 UTC, justinro-underscore commented on Assets/Scripts/GameElements/EnemyMovementController.cs
> +                    if (subChild.tag == Constants.waypointTag)
Same here!

2023-09-16 22:35 UTC, justinro-underscore commented on Assets/Scripts/GameElements/EnemyMovementController.cs
> +    private struct Path
I think Unity doesn't really like structs all that much. I'd recommend making this a class

2023-09-16 22:35 UTC, justinro-underscore approved these changes
Meant to approve! 💩

2023-09-16 23:42 UTC, vchadha commented on Assets/Scripts/GameElements/EnemyMovementController.cs
> +    private struct Path
Unity whyyyyyy

2023-09-16 23:52 UTC, merged